SETTINGS_INSTANCE = (
    "# sprites_file_name: str\n"
    "..\\resource\\sprites.bmp\n"
    "# sprites_separator_width: int (>= 0)\n"
    "1\n"
    "# sprites_transparent_color: Color (r/g/b - 0..255 each)\n"
    "255 0 255\n"
    "# cell_size: Size  # sprites (pixels) (> 0 each)\n"
    "50 50\n"
    "# cursor_alpha: int (0..255)\n"
    "20\n"
    "# background_file_name: str\n"
    "..\\resource\\background.bmp\n"
    "# icon_file_name: str\n"
    "..\\resource\\icon.bmp\n"
    "# icon_transparent_color: Color (r/g/b - 0..255 each)\n"
    "255 0 255\n"
    "# show_cursor: bool (0 - yes or 1 - no)\n"
    "1\n"
    "# message_text_color: Color (r/g/b - 0..255 each)\n"
    "255 201 14\n"
    "# message_background_color: Color (r/g/b - 0..255 each)\n"
    "0 0 61\n"
    "# message_frame_color: Color (r/g/b - 0..255 each)\n"
    "255 201 14\n"
    "# message_alpha: int (0..255)\n"
    "220\n"
    "# message_font_size: int (> 5)\n"
    "25\n"
    "# message_frame_width: int (>= 0)\n"
    "1\n"
    "# message_vert_indent: int (>= 0)\n"
    "10\n"
    "# message_hor_indent: int (>= 0)\n"
    "10\n"
)
